{{- $secretName := "itlminio01-env-configuration" -}}
{{- $namespace := .Release.Namespace -}}
{{- $existingSecret := lookup "v1" "Secret" $namespace $secretName -}}

{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/instance: itl-minio01
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="nwa"
    export MINIO_ROOT_PASSWORD="{{ include "randomString" . }}"
    export CONSOLE_TLS_PORT="443"
    export CONSOLE_TLS_HOSTNAME="itlminio01-console.dev.itlusions.com"
    export MINIO_BROWSER_REDIRECT_URL="https://itlminio01-console.dev.itlusions.com/"
{{- else }}
{{- $existingSecret.data.config.env | b64dec | nindent 2 }}
{{- end }}