{{- if (.Values.secrets) }}
{{- fail "# ERROR: '.secrets' is deprecated since v5.0.15 and has been removed. Please use '.tenant.configSecret' instead." }}
{{- else }}
{{- if not (.Values.tenant.configSecret) }}
{{- fail "# ERROR: '.tenant.configSecret' should be set." }}
{{- else }}
{{- if not (.Values.tenant.consoleTlsHostname) }}
{{- fail "# ERROR: '.tenant.consoleTlsHostname' should be set." }}
{{- else }}
{{- if not (.Values.tenant.minioBrowserRedirectUrl) }}
{{- fail "# ERROR: '.tenant.minioBrowserRedirectUrl' should be set." }}
{{- else }}
{{- if not (.Values.tenant.configSecret.existingSecret) }}
{{- $secretName := dig "tenant" "configSecret" "name" "" (.Values | merge (dict)) -}}

{{- $namespace := .Release.Namespace -}}
{{- $existingSecret := lookup "v1" "Secret" $namespace $secretName -}}

{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ dig "tenant" "configSecret" "name" "" (.Values | merge (dict)) }}
  labels:
    app.kubernetes.io/instance: {{ .Values.tenant.name | default "minios3" | quote }}
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER={{ .Values.tenant.configSecret.accessKey | default "nwa" | quote }}
    export MINIO_ROOT_PASSWORD={{ .Values.tenant.configSecret.secretKey | default (randAlphaNum 20) | b64enc | quote }}
    export CONSOLE_TLS_PORT={{ .Values.tenant.consoleTlsPort | default "443" | quote }}
    export CONSOLE_TLS_HOSTNAME={{ .Values.tenant.consoleTlsHostname | default "example-console.dev.itlusions.com" | quote }}
    export MINIO_BROWSER_REDIRECT_URL={{ .Values.tenant.minioBrowserRedirectUrl | default "https://example-console.dev.itlusions.com/" | quote }}

{{- else }}
{{- $existingSecret.data.config.env | b64dec | nindent 2 }}
{{- end }}
{{- else }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}